spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19970410

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.wangwang: info
  file:
    name: log/movie-pro.log
server:
  port: 8081